[workspace]
members = [
    "crates/ulc",
    "crates/ulc_ast",
    "crates/ulc_builder",
    "crates/ulc_checker",
    "crates/ulc_codegen_cranelift",
    "crates/ulc_lexer",
    "crates/ulc_parser",
    "crates/ulc_types",
]