[package]
name = "ulc_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
codespan-reporting = "0.11.1"
logos = "0.12.0"